packages:
  - packages/*
publicHoistPattern:
  - "*prettier*"
overrides:
  vite: catalog:build
catalogs:
  build:
    tsdown: ^0.18.4
    typescript: ^5.9.3
    vite: npm:rolldown-vite@latest
  cli:
    pncat: ^0.7.7
  lint:
    "@eslint-react/eslint-plugin": ^2.5.0
    "@eslint/js": ^9.39.2
    "@eslint/markdown": ^7.5.1
    "@prettier/plugin-xml": 3.4.2
    "@stylistic/eslint-plugin": 5.2.3
    "@vitest/eslint-plugin": ^1.6.4
    astro-eslint-parser: ^1.2.2
    eslint: ^9.39.2
    eslint-config-flat-gitignore: 2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-better-tailwindcss: ^3.8.0
    eslint-plugin-command: ^3.4.0
    eslint-plugin-format: ^1.1.0
    eslint-plugin-import-lite: ^0.4.0
    eslint-plugin-jsdoc: ^61.5.0
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-perfectionist: ^5.2.0
    eslint-plugin-pnpm: ^1.4.3
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-svelte: ^3.13.1
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-yml: ^1.19.1
    eslint-typegen: ^2.3.0
    jsonc-eslint-parser: ^2.4.2
    prettier: ^3.7.4
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-svelte: ^3.4.1
    publint: ^0.3.16
    svelte-eslint-parser: ^1.4.1
    toml-eslint-parser: ^0.10.1
    typescript-eslint: ^8.51.0
    yaml-eslint-parser: ^1.3.2
  monorepo:
    eslint-config-turbo: ^2.7.2
  node:
    globals: ^17.0.0
    local-pkg: ^1.1.2
  script:
    tsx: ^4.21.0
  style:
    tailwindcss: ^4.1.18
  types:
    "@types/node": ^25.0.3
    "@typescript-eslint/eslint-plugin": ^8.51.0
    "@typescript-eslint/parser": ^8.51.0
