packages:
  - packages/*

overrides:
  vite: npm:rolldown-vite@latest
catalogs:
  build:
    tsdown: ^0.15.7
    typescript: ^5.9.3
  cli:
    pncat: ^0.7.1
  lint:
    "@eslint-react/eslint-plugin": ^2.2.2
    "@eslint/js": ^9.38.0
    "@eslint/markdown": ^7.4.0
    "@prettier/plugin-xml": 3.4.2
    "@stylistic/eslint-plugin": 5.2.3
    "@vitest/eslint-plugin": ^1.3.23
    astro-eslint-parser: ^1.2.2
    eslint: ^9.38.0
    eslint-config-flat-gitignore: 2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-better-tailwindcss: ^3.7.10
    eslint-plugin-command: ^3.3.1
    eslint-plugin-format: ^1.0.2
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^61.1.4
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.3.0
    eslint-plugin-react-hooks: ^7.0.0
    eslint-plugin-react-refresh: ^0.4.24
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-svelte: ^3.12.4
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^61.0.2
    eslint-plugin-unused-imports: ^4.2.0
    eslint-plugin-yml: ^1.19.0
    eslint-typegen: ^2.3.0
    jsonc-eslint-parser: ^2.4.1
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-svelte: ^3.4.0
    publint: ^0.3.14
    svelte-eslint-parser: ^1.3.3
    toml-eslint-parser: ^0.10.0
    typescript-eslint: ^8.46.1
    yaml-eslint-parser: ^1.3.0
  monorepo:
    eslint-config-turbo: ^2.5.8
  node:
    globals: ^16.4.0
    local-pkg: ^1.1.2
  script:
    tsx: ^4.20.6
  style:
    tailwindcss: ^4.1.14
  types:
    "@types/node": ^24.8.1
    "@typescript-eslint/eslint-plugin": ^8.46.1
    "@typescript-eslint/parser": ^8.46.1
